### ISSUE TITLE
Duplicates being created

### ISSUE THREAD

**Issue by phuibonhoa** [akhudek/google-photos-to-apple-photos#1]
When Photos starts throwing errors, what is the recommended action to take?

I've been doing ctrl+c on the script and force quitting Photos, then restarting the script, but I think that's creating a ton of duplicates in my album.  

Should I let the script run to completion? I think it will take a long time to finish importing photos though because it has to go through all the photos even though none will actually be imported.

**Comment by akhudek** [comment]
The script should record photos it's already imported. I encountered the same issue as you and my solution was just to stop the script periodically (before photos starts erroring), then restart photos and restart the script. When you restart the script it will skip all the photos it already recorded as having processed.

There are some other suggestions I put in the readme file, but I haven't tried them and don't know if they will work. It would actually be easy enough to modify the script to automatically stop after X new photos are imported to make it more convenient I guess.

**Comment by phuibonhoa** [comment]
Ahh good to know. I wasn’t sure if ctrl + c was a bad way to stop the script and causing my duplicates. I’ll keep at it, and at worst can just run something after to try to remove dup. thanks!

**Comment by akhudek** [comment]
You can modify the script like so to make it stop automatically after every batch of 40 photos added. Could help you avoid duplicates. In practice I used a modification like this.

```
count = 0
for folder, image_file in photos(sys.argv[1]):
    if count >= 40:
        exit(1)
    if (
        folder not in processed_albums
        and image_file != ".DS_Store"
        and image_file != "archive_browser.html"
    ):
        image_path = os.path.join(folder, image_file)
        image_timestamp = photo_timestamp(image_path)
        id = add_photo(image_path, image_file, image_timestamp)
        if not id == "":
            print("Skipped as it already exists")
        else:
            count += 1
            print(f"Imported {image_file}")
```

**Comment by phuibonhoa** [comment]
Ahhh that's great, thank you!
